# Configuration for Crossover Events Trading
# This configuration uses the vault42.crossover_events table for signal generation

# Signal strategy configuration
signal_strategy:
  enable_predictions: true          # Enable crossover events from vault42.crossover_events
  enable_news_alerts: false         # Disable news alert signals
  crossover_cooldown_minutes: 5     # Cooldown period between crossover signals for same ticker

# Order timing configuration
order_timing:
  entry_order_timeout: 10            # Seconds for ENTRY orders (GTD)
  exit_order_timeout: 10            # Seconds for EXIT/DANGLING_SHARES orders (GTD)

executions:
  AAPL:
    ticker: AAPL
    bearish_lower_bound: 1.0
    bearish_upper_bound: 1.01
    bullish_lower_bound: 0.0
    bullish_upper_bound: 1.01
    unit_position_size: 250
    max_position_size: 750
    trade_threshold: 180
    max_hold_time: 900
    take_profit_target: 0.002
    stop_loss_target: 0.005
    stop_loss_strat: STATIC
    spread_strategy: WORST
    spread_offset: 0
    inverted: regular

  META:
    ticker: META
    bearish_lower_bound: 1.0
    bearish_upper_bound: 1.01
    bullish_lower_bound: 0.0
    bullish_upper_bound: 1.01
    unit_position_size: 100
    max_position_size: 300
    trade_threshold: 180
    max_hold_time: 900
    take_profit_target: 0.002
    stop_loss_target: 0.005
    stop_loss_strat: STATIC
    spread_strategy: WORST
    spread_offset: 0
    inverted: regular

  TSLA:
    ticker: TSLA
    bearish_lower_bound: 1.0
    bearish_upper_bound: 1.01
    bullish_lower_bound: 0.0
    bullish_upper_bound: 1.01
    unit_position_size: 250
    max_position_size: 750
    trade_threshold: 180
    max_hold_time: 900
    take_profit_target: 0.002
    stop_loss_target: 0.005
    stop_loss_strat: STATIC
    spread_strategy: WORST
    spread_offset: 0
    inverted: regular

  AMZN:
    ticker: AMZN
    bearish_lower_bound: 1.0
    bearish_upper_bound: 1.01
    bullish_lower_bound: 0.0
    bullish_upper_bound: 1.01
    unit_position_size: 250
    max_position_size: 750
    trade_threshold: 180
    max_hold_time: 900
    take_profit_target: 0.002
    stop_loss_target: 0.005
    stop_loss_strat: STATIC
    spread_strategy: WORST
    spread_offset: 0
    inverted: regular

  GOOG:
    ticker: GOOG
    bearish_lower_bound: 1.0
    bearish_upper_bound: 1.01
    bullish_lower_bound: 0.0
    bullish_upper_bound: 1.01
    unit_position_size: 250
    max_position_size: 750
    trade_threshold: 180
    max_hold_time: 900
    take_profit_target: 0.002
    stop_loss_target: 0.005
    stop_loss_strat: STATIC
    spread_strategy: WORST
    spread_offset: 0
    inverted: regular

  MSFT:
    ticker: MSFT
    bearish_lower_bound: 1.0
    bearish_upper_bound: 1.01
    bullish_lower_bound: 0.0
    bullish_upper_bound: 1.01
    unit_position_size: 250
    max_position_size: 750
    trade_threshold: 180
    max_hold_time: 900
    take_profit_target: 0.002
    stop_loss_target: 0.005
    stop_loss_strat: STATIC
    spread_strategy: WORST
    spread_offset: 0
    inverted: regular

# Position block defined ONCE at the top level
position:
  max_loss_per_trade: 7600
  max_loss_cumulative: 7600
  clip_activation: 8000
  clip_stop_loss: 2000

# Model name defined ONCE at the top level
model_name: crossover_v1.0
